"""
Django settings for blog_project project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ==============================================================================
# SECURITY SETTINGS
# ==============================================================================

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@rbi2!w#f=kea!o(53!qv__q-hppxx339t)uh&9t82w(i-%*am'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Host/domain names that this Django site can serve
if DEBUG:
    # Development: Allow localhost and ngrok for testing
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '.ngrok-free.dev']
else:
    # Production: Read from environment variable
    raw = os.environ.get('ALLOWED_HOSTS', '')
    ALLOWED_HOSTS = [h.strip() for h in raw.split(',') if h.strip()]

# ==============================================================================
# APPLICATION DEFINITION
# ==============================================================================

INSTALLED_APPS = [
    # Django core apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'corsheaders',      # Cross-Origin Resource Sharing
    'rest_framework',   # Django REST Framework
    
    # Local apps
    'blog',
]

MIDDLEWARE = [
    # CORS middleware must be at the top
    'corsheaders.middleware.CorsMiddleware',
    
    # Django core middleware
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'blog_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blog_project.wsgi.application'

# ==============================================================================
# DATABASE
# ==============================================================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ==============================================================================
# PASSWORD VALIDATION
# ==============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ==============================================================================
# INTERNATIONALIZATION
# ==============================================================================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ==============================================================================
# STATIC FILES & MEDIA
# ==============================================================================

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ==============================================================================
# CORS & SECURITY SETTINGS
# ==============================================================================

# CORS (Cross-Origin Resource Sharing) Configuration
if DEBUG:
    # Development: Allow all origins for testing convenience
    CORS_ALLOW_ALL_ORIGINS = True
    
    # Specific trusted origins for development
    CORS_ALLOWED_ORIGINS = [
        'http://localhost:3000',      # Nuxt dev server
        'http://127.0.0.1:3000',      # Nuxt dev server (alternative)
        'http://127.0.0.1:8000',      # Django dev server
        'https://irayaapitesting.netlify.app',  # Netlify frontend
        'https://wearisome-rosanna-semicynically.ngrok-free.dev',  # Current ngrok tunnel
    ]
    
    # CSRF trusted origins for admin interface
    CSRF_TRUSTED_ORIGINS = [
        'http://localhost:8000',
        'http://127.0.0.1:8000',
        'https://wearisome-rosanna-semicynically.ngrok-free.dev',  # Update when ngrok restarts
    ]
else:
    # Production: Strict CORS configuration
    CORS_ALLOW_ALL_ORIGINS = False
    
    # Production CORS allowed origins (set via environment variable)
    raw_cors = os.environ.get('CORS_ALLOWED_ORIGINS', '')
    CORS_ALLOWED_ORIGINS = [v.strip() for v in raw_cors.split(',') if v.strip()]
    
    # Production CSRF trusted origins
    raw_csrf = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
    CSRF_TRUSTED_ORIGINS = [v.strip() for v in raw_csrf.split(',') if v.strip()]

# ==============================================================================
# DEFAULT PRIMARY KEY FIELD TYPE
# ==============================================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'