# Generated by Django 5.0.3 on 2025-11-29 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_remove_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='publication_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='publications.publication')),
            ],
            options={
                'verbose_name': 'Publication Image',
                'verbose_name_plural': 'Publication Images',
                'ordering': ['created_at'],
            },
        ),
    ]
