# Generated by Django 5.0.3 on 2025-11-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_publicationimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='description',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='location',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='publication_type',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='published',
        ),
        migrations.AddField(
            model_name='publication',
            name='alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='publication',
            name='button_color',
            field=models.CharField(default='primary', max_length=50),
        ),
        migrations.AddField(
            model_name='publication',
            name='button_on_hover',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publication',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='content1',
            field=models.TextField(blank=True, help_text='First list item'),
        ),
        migrations.AddField(
            model_name='publication',
            name='content2',
            field=models.TextField(blank=True, help_text='Second list item'),
        ),
        migrations.AddField(
            model_name='publication',
            name='content_type',
            field=models.CharField(choices=[('content', 'Content'), ('list', 'List')], default='content', max_length=10),
        ),
        migrations.AddField(
            model_name='publication',
            name='elevation',
            field=models.CharField(blank=True, default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='publication',
            name='email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='publications/images/'),
        ),
        migrations.AddField(
            model_name='publication',
            name='rounded_img',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publication',
            name='show_button',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='sub_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='publication',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='publication',
            name='video_id',
            field=models.CharField(blank=True, help_text='YouTube Video ID', max_length=255),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Upload PDF file for download button', null=True, upload_to='publications/'),
        ),
    ]
