# Generated by Django 5.0.3 on 2026-01-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_tag_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='static_image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
