# Generated by Django 5.0.3 on 2026-02-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_static_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
