# Generated by Django 5.0.3 on 2026-02-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_published_alter_post_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sub_text', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('content_type', models.CharField(default='content', max_length=20)),
                ('content1', models.TextField(blank=True, null=True)),
                ('content2', models.TextField(blank=True, null=True)),
                ('type', models.CharField(default='image', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='publications/')),
                ('static_image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('video_id', models.CharField(blank=True, max_length=100, null=True)),
                ('download_link', models.URLField(blank=True, max_length=500, null=True)),
                ('show_button', models.BooleanField(default=True)),
                ('button_on_hover', models.BooleanField(default=False)),
                ('button_color', models.CharField(default='primary', max_length=50)),
                ('elevation', models.CharField(default='0', max_length=10)),
                ('email', models.BooleanField(default=False)),
                ('rounded_img', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
