# Generated by Django 5.0.3 on 2026-02-28 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_post_images_postimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='post',
            name='static_image_path',
        ),
    ]
