# Generated by Django 5.0.3 on 2026-02-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brochure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='brochures/')),
                ('image_max_width', models.CharField(default='400px', max_length=50)),
                ('image_max_height', models.CharField(default='380px', max_length=50)),
                ('card_height', models.IntegerField(default=350)),
                ('text_content', models.TextField()),
                ('text_column_classes', models.CharField(default='pl-xl-2 pl-md-16 mt-6', max_length=255)),
                ('button_elevation', models.CharField(default='3', max_length=50)),
                ('button_color', models.CharField(default='primary-lighten-1', max_length=50)),
                ('button_hover_success', models.BooleanField(default=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='brochures/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
