# Generated by Django 6.0.1 on 2026-03-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_brochure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='download_link',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='static_image_path',
        ),
        migrations.AddField(
            model_name='publication',
            name='pdf_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='publications/files/'),
        ),
    ]
