# Generated by Django 5.2.7 on 2025-11-18 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_tag_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_images/')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of image in gallery (lower numbers appear first)')),
                ('is_cover', models.BooleanField(default=False, help_text='Mark this image as the cover/featured image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.post')),
            ],
            options={
                'verbose_name': 'Post Image',
                'verbose_name_plural': 'Post Images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
