# Generated by Django 5.2.7 on 2025-11-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_post_status_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
